### ISSUE TITLE
The OP players when they join they become "the ball"

### ISSUE THREAD

**Issue by Zeltuv** [Shynixn/BlockBall#489] opened 2024-01-28 16:06 UTC
Hey, so we paid the patreon and got the legacy version (we are based on 1.8.8), everything works fine except one weird bug that happens only when we have the plugin on the server, is that we "become" the ball and our view is just rolling on every side and create an "epileptic" effect. I don't know how better I can explain this issue. Thanks in advance for your time.

**Comment by Shynixn** [comment] 2024-01-28 16:45
Hi, that sounds like a very weird bug. I did test it again with 1.8.8 and multiple players but I did not encounter this issue. 
BlockBall manually sends entity packets (spawn, how the ball looks like, rotation) to your client. There may be a plugin doing packet manipulation on your server, which may cause this issue? If so, I would like to implement a fix in BlockBall.

Can you please give me detailed description how to replicate this issue?
How many players suffer from the issue? Only the one joining the game or all players?

In this particular case, I would even offer to join your server and take a look at it myself, if you want.

**Comment by Zeltuv** [comment] 2024-01-28 19:40
Hey, thanks for getting back that fast, we did test with only two plugins, yours and viaversion and it kept on doing the bug, here is the IP of the server: mc.wonderlands.ge. Thanks for your precious time.

**Comment by Shynixn** [comment] 2024-01-29 07:47
I think I found a problem in BlockBall. Can you please send me your patreon name? I will send you a private message with a link to a new BlockBall version containing the change.

**Comment by Zeltuv** [comment] 2024-01-29 14:12
Sure, the name is Ryzen23.

**Comment by Shynixn** [comment] 2024-01-29 14:52
Done, please test if the problem is now fixed.

**Closed** 2024-02-24 16:46 UTC
Labels: bug
